---
- name: Compute the Docker daemon options
  ansible.builtin.set_fact:
    docker_role_daemon_options: >-
      {{
        docker_daemon_options
        | combine({'dns': homelab_docker_dns_servers, 'dns-search': homelab_docker_dns_search})
        if homelab_docker_dns_enabled | bool
        else docker_daemon_options
      }}

- name: Install and configure Docker
  ansible.builtin.include_role:
    name: geerlingguy.docker
  vars:
    docker_edition: ce
    docker_install_compose_plugin: true
    docker_users:
      - "{{ ansible_user }}"
    docker_daemon_options: "{{ docker_role_daemon_options }}"
